<?php

class Job
{
    private $db;

    public function __construct()
    {
        $this->db = Database::getInstance()->getConnection();
    }

    // Lookup Employer ID based on the authenticated User ID
    public function getEmployerIdByUserId($userId)
    {
        $sql = "SELECT employer_id FROM employers WHERE user_id = :user_id LIMIT 1";
        $stmt = $this->db->prepare($sql);
        $stmt->execute([':user_id' => $userId]);
        $result = $stmt->fetch();
        return $result ? $result['employer_id'] : false;
    }

    public function getMunicipalities()
    {
        $sql = "SELECT municipality_id, municipality_name FROM lib_municipalities ORDER BY municipality_name ASC";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getMasterSkills()
    {
        // V2 Upgrade: Join with categories to allow organized UI rendering
        $sql = "SELECT ms.skill_id, ms.skill_name, sc.category_name 
                FROM master_skills ms
                LEFT JOIN skill_categories sc ON ms.category_id = sc.category_id
                WHERE ms.status = 'approved'
                ORDER BY sc.category_name ASC, ms.skill_name ASC";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    // Fetch all active job seekers to feed into the AI Engine loop
    public function getActiveJobSeekers()
    {
        $sql = "SELECT js.jobseeker_id 
                FROM job_seekers js
                JOIN users u ON js.user_id = u.user_id
                WHERE u.account_status = 'Active'";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function createJobPosting($employerId, $jobData, $selectedSkills)
    {
        try {
            $this->db->beginTransaction();

            // 1. Insert Core Job Details (Strict lowercase table name)
            $sqlJob = "INSERT INTO job_postings 
                (employer_id, job_title, job_description, required_experience, salary_range, employment_type, municipality_id, job_status) 
                VALUES (:employer_id, :job_title, :job_description, :required_experience, :salary_range, :employment_type, :municipality_id, 'Open')";

            $stmtJob = $this->db->prepare($sqlJob);
            $stmtJob->execute([
                ':employer_id' => $employerId,
                ':job_title' => $jobData['job_title'],
                ':job_description' => $jobData['job_description'],
                ':required_experience' => $jobData['required_experience'],
                ':salary_range' => $jobData['salary_range'],
                ':employment_type' => $jobData['employment_type'],
                ':municipality_id' => $jobData['municipality_id']
            ]);

            // 2. Securely fetch the exact auto-incremented job_id generated by the previous query
            $newJobId = $this->db->lastInsertId();

            // 3. Map the Required Skills dynamically (Mandatory/Optional)
            $sqlSkill = "INSERT INTO job_required_skills (job_id, skill_id, requirement_type) 
                         VALUES (:job_id, :skill_id, :req_type)";
            $stmtSkill = $this->db->prepare($sqlSkill);

            foreach ($selectedSkills as $skillId => $reqType) {
                $stmtSkill->bindValue(':job_id', $newJobId);
                $stmtSkill->bindValue(':skill_id', $skillId);
                $stmtSkill->bindValue(':req_type', $reqType);
                $stmtSkill->execute();
            }

            $this->db->commit();

            // Return the newly created job_id so the Controller can trigger the AI engine in Part 3
            return $newJobId;

        } catch (PDOException $e) {
            $this->db->rollBack();
            error_log("Job Posting Transaction Failed: " . $e->getMessage());
            return false;
        }
    }
}