<?php

class Job
{
    private $db;

    public function __construct()
    {
        $this->db = Database::getInstance()->getConnection();
    }

    // Lookup Employer ID based on the authenticated User ID
    public function getEmployerIdByUserId($userId)
    {
        $sql = "SELECT employer_id FROM Employers WHERE user_id = :user_id LIMIT 1";
        $stmt = $this->db->prepare($sql);
        $stmt->execute([':user_id' => $userId]);
        $result = $stmt->fetch();
        return $result ? $result['employer_id'] : false;
    }

    public function getBarangays()
    {
        $sql = "SELECT barangay_id, barangay_name FROM Barangays ORDER BY barangay_name ASC";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getMasterSkills()
    {
        $sql = "SELECT skill_id, skill_name FROM Master_Skills ORDER BY skill_name ASC";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    // Fetch all active job seekers to feed into the AI Engine loop
    public function getActiveJobSeekers()
    {
        $sql = "SELECT js.jobseeker_id 
                FROM Job_Seekers js
                JOIN Users u ON js.user_id = u.user_id
                WHERE u.account_status = 'Active'";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function createJobPosting($employerId, $jobData, $skillIds)
    {
        try {
            $this->db->beginTransaction();

            // 1. Insert Core Job Details
            $sqlJob = "INSERT INTO Job_Postings 
                (employer_id, job_title, job_description, required_experience, salary_range, employment_type, barangay_id, job_status) 
                VALUES (:employer_id, :job_title, :job_description, :required_experience, :salary_range, :employment_type, :barangay_id, 'Open')";

            $stmtJob = $this->db->prepare($sqlJob);
            $stmtJob->execute([
                ':employer_id' => $employerId,
                ':job_title' => $jobData['job_title'],
                ':job_description' => $jobData['job_description'],
                ':required_experience' => $jobData['required_experience'],
                ':salary_range' => $jobData['salary_range'],
                ':employment_type' => $jobData['employment_type'],
                ':barangay_id' => $jobData['barangay_id']
            ]);

            // 2. Securely fetch the exact auto-incremented job_id generated by the previous query
            $newJobId = $this->db->lastInsertId();

            // 3. Map the Required Skills (Setting default requirement_type to 'Mandatory')
            $sqlSkill = "INSERT INTO Job_Required_Skills (job_id, skill_id, requirement_type) 
                         VALUES (:job_id, :skill_id, 'Mandatory')";
            $stmtSkill = $this->db->prepare($sqlSkill);

            foreach ($skillIds as $skillId) {
                $stmtSkill->bindValue(':job_id', $newJobId);
                $stmtSkill->bindValue(':skill_id', $skillId);
                $stmtSkill->execute();
            }

            $this->db->commit();

            // Return the newly created job_id so the Controller can trigger the AI engine in Part 3
            return $newJobId;

        } catch (PDOException $e) {
            $this->db->rollBack();
            error_log("Job Posting Transaction Failed: " . $e->getMessage());
            return false;
        }
    }
}